---
title: John Paul Brammer
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    layout: post
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    hero: 
    featured: 
    feature-number: 
    image: 
    publisher: 
    original: 
    quote: 
    permalink: "/work/:title/"
    video-link: 
    video: 
name: John Paul Brammer
markdown: kramdown
exclude:
- node_modules
- gulpfile.js
- package.json
permalink: pretty
baseurl: "/"
url: http://www.johnpaulbrammer.com
email: jpbrammer@gmail.com
twitter: jpbrammer
description: Bold cultural and political commentary from America's margins.
longform-description: 'John Paul Brammer is a writer, speaker, and activist based
  in New York City. His work has been published in The Guardian, Slate, BuzzFeed,
  NBC, and many other outlets. His work blends the deeply personal with the political.
  Samples of his writing, including essays, memoirs, and features can be found here
  on his website. '
file: 
