---
title: John Paul Brammer
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    layout: post
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    hero: 
    featured: 
    feature-number: 
    image: 
    publisher: 
    original: 
    quote: 
    permalink: "/work/:title/"
    video-link: 
    video: 
name: John Paul Brammer
markdown: kramdown
exclude:
- node_modules
- gulpfile.js
- package.json
permalink: pretty
baseurl: "/"
url: http://www.johnpaulbrammer.com
email: jpbrammer@gmail.com
twitter: jpbrammer
description: Bold cultural and political commentary from America's margins.
longform-description: Bold cultural and political commentary from America's margins.
file: 
