---
title: John Paul Brammer
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    layout: post
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    hero: 
    featured: 
    feature-number: 
    image: 
    publisher: 
    original: 
    quote: 
    permalink: "/work/:title/"
    video-link: 
    video: 
name: John Paul Brammer
markdown: kramdown
exclude:
- node_modules
- gulpfile.js
- package.json
permalink: pretty
baseurl: "/"
url: http://www.johnpaulbrammer.com
email: jpbrammer@gmail.com
twitter: jpbrammer
description: Bold cultural and political commentary from America's margins.
longform-description: Candid, passionate about issues that matter and humorous about
  things that don't. Absurd comedy mixed with astute observations. Lorem ipsum dolor
  sit amet, cum ne lorem moderatius definiebas, et vis vide sonet quodsi, vim eu viris
  conclusionemque. Vel id utinam liberavisse. Id voluptua ponderum comprehensam eos,
  mel fastidii explicari assentior ad. Ex harum aliquam petentium per, at eos dolorem
  platonem, virtute percipit
file: "/uploads/John%20Paul%20Brammer%20%7C%20Media%20Kit.zip"
